### ISSUE TITLE
Not working for different timesteps at encoder and decoder

### ISSUE THREAD

**Issue by NehaTamore** [thushv89/attention_keras#13]
It can't handle sequences of different lengths at encoder and decoder. For example, when en_timesteps, fr_timesteps are different it can't concatenate encoder_output and decoder_output, as an input to attention layer

**Comment by thushv89** [comment]
Hi @NehaTamore ,

Thanks for letting me know. I will look into this.

**Comment by thushv89** [comment]
I am not sure what this error is. If you can post your code and the stacktrace I can help you further. But I already ran the code with different sequence lenghts and it word fine on my end. Feel free to reopen the issue if it's still there.
