### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by KonstantinaLazaridou** [thushv89/attention_keras#16]
Hey, thanks for sharing your code for attention in Keras.
I tried to install the package with `pip install git+https://github.com/thushv89/attention_keras.git`, (having already activated my current conda environment for deep learning experiments) and this is the error I get:
```Collecting git+https://github.com/thushv89/attention_keras.git
  Cloning https://github.com/thushv89/attention_keras.git to /tmp/pip-req-build-qrcv9rfd
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/konstantina/anaconda3/envs/my_env/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-qrcv9rfd/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-qrcv9rfd/
```

Any idea why?

**Comment by thushv89** [comment]
@KonstantinaLazaridou ,

Sorry about the long delay in the response. I was busy with some work and didn't have time to follow the issues in this repo. That's a strange error. If you're still having the issue, can you tell me the steps you followed to get this?
