### ISSUE TITLE
TypeError: The added layer must be an instance of class Layer.

### ISSUE THREAD

**Issue by KonstantinaLazaridou** [thushv89/attention_keras#17]
Hey, I included your code as a Python package in my Pycharm project and imported it like this `from my_project.attention.layers.attention import AttentionLayer` in my script. Then I created the attention layer in the way that is shown in the README: `attn_layer = AttentionLayer(name='attention_layer');`.

The code for creating my model is:
```model = Sequential();
    embedding_layer = set_up_embedding_layer(word_idx_training, em_dim, maximum_sequence_length, embedding_type);
    model.add(embedding_layer);
    attn_layer = AttentionLayer(name='attention_layer');
    model.add(attn_layer);
    model.add(LSTM(16));
    model.add(Dense(int(class_number), activation='softmax'));
```

When I run the script, I am getting an error message that the attention layer is not of class `Layer`. I understand that the layer is intended to work with GRUs, but nonetheless it looks like your class `AttentionLayer` is of type `Layer`. Is this correct? And, can I use the attention mechanism as I show above, or only by concatanating the attention input and the decoder GRU output?

Thanks

**Comment by thushv89** [comment]
@KonstantinaLazaridou 

Regarding your question, 

> but nonetheless it looks like your class AttentionLayer is of type Layer. Is this correct

Yes, that's correct.

> And, can I use the attention mechanism as I show above, or only by concatanating the attention input and the decoder GRU output?

So, I am not completely sure if you can use this layer as you've shown. Initially, I only thought about using this with sequential models. If you can provide more details (may be a diagram of what you're trying to create, I might be able to help.

**Comment by thushv89** [comment]
If you still would like to follow up, please recreate the issue in the new provided template.
