### ISSUE TITLE
AttributeError: 'tuple' object has no attribute '_keras_mask'

### ISSUE THREAD

**Issue by AlanGanem** [thushv89/attention_keras#18]
I'm having this problem after reshaping the tensors 'encoder_out' and 'decoder_out', in order for its shapes to be explicit and avoid the error adressed in [https://github.com/thushv89/attention_keras/issues/9](url). 
But then i get the following error:

File "C:\Users\ganem\AppData\Local\Programs\Python\Python36\Lib\site-packages\tensorflow\python\layers\base.py", line 738, in __call__
    outputs._keras_mask = output_mask  # pylint: disable=protected-access

AttributeError: 'tuple' object has no attribute '_keras_mask'

Heres the full code:

`
#import modules

import tensorflow as tf
from attention import AttentionLayer
from tensorflow.python.keras.layers import Input, GRU, Dense, Concatenate, TimeDistributed
from tensorflow.python.keras.models import Model
from tensorflow.python.keras.callbacks import EarlyStopping
from tensorflow.python.keras.layers import Dropout, Concatenate ,Dense ,LSTM,MaxPooling1D ,Conv1D, MaxPooling1D,Input, TimeDistributed, Flatten, Conv2D,Reshape,Permute, Flatten
from tensorflow.python.keras.models import Model, Sequential
from tensorflow.python.keras.utils import plot_model
import TimeSeriesUtils as TSU
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
import pandas as pd
import numpy as np

# set model params

latent_dim = 10
look_back_period = 12
pred_period = 8
dropout_rate = 0.5
batch_size = 128

#read data and convert to np array

data = pd.read_table(r'~\gas_prices_brazil\2004-2019.tsv',delim_whitespace=False,header=0)
data['DATA INICIAL'] = pd.to_datetime(data['DATA INICIAL'])
data['DATA FINAL'] = pd.to_datetime(data['DATA FINAL'])
data.set_index('DATA FINAL',inplace = True)
data.replace('-',np.nan, inplace = True)
number_columns = []
for column in data.columns:
        try:
            data[column] = data[column].astype(float)     
            number_columns.append(column)
            print(column)
        except:    
            pass    

features = ['PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA', 'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA', 'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO', 'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO', 'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO']
train_data = data[(data['ESTADO'] == 'SAO PAULO') & (data['PRODUTO'] == 'GASOLINA COMUM')].resample('W').mean()
train_data = train_data[features]

scaled_featues = []
dependent_variable = ['PREÇO MÉDIO REVENDA']
train_data = train_data[features+dependent_variable]
train_data = train_data.fillna(method = 'ffill', limit = 300)
train_data = train_data.astype('float')
assert not any(any(train_data.isna()))

X = TSU.chunk_data_by_date(train_data.values,pred_period,look_back_period)
X_train, y_train, X_val, y_val = X
X_train_teacher_forcing,X_val_teacher_forcing,X_train_no_teacher_forcing,X_val_no_teacher_forcing = TSU.teacher_forcing_generator(y_train,y_val)

# defining layers

encoder_input = Input(shape = (X_train.shape[1],X_train.shape[2]),batch_size = 128,name = 'encoder_input')
decoder_input = Input(shape = (look_back_period,1),batch_size = 128,name = 'decoder_input')

encoderLSTM = LSTM(units = latent_dim,return_state = True,return_sequences = True,name = 'enc_LSTM',dropout = dropout_rate)
attention1 = AttentionLayer()
decoderLSTM = LSTM(units = latent_dim,return_state = True,return_sequences = True,name = 'dec_LSTM',dropout = dropout_rate)
dense_output = TimeDistributed(Dense(1, activation = 'relu'),name = 'time_distirbuted_dense_output')

# building model

encoder_out, encoder_states = encoderLSTM(encoder_input)[0], encoderLSTM(encoder_input)[1:]

decoder_out, decoder_states = decoderLSTM(decoder_input,initial_state = encoder_states)[0],decoderLSTM(decoder_input,initial_state = encoder_states)[1:]

output = dense_output(decoder_out)

# explicitly define tensor shapes as TensorShape([Dimension(128), Dimension(12), Dimension(10)]) and TensorShape([Dimension(128), Dimension(8), Dimension(10)])
decoder_out.set_shape((tf.Dimension(batch_size),tf.Dimension(8),tf.Dimension(10)))
encoder_out.set_shape((tf.Dimension(batch_size),tf.Dimension(12),tf.Dimension(10)))

attention1_out, attention1_states = attention1([encoder_out, decoder_out])
`

i get the error in the last line

any heads up on this issue?

**Comment by thushv89** [comment]
@AlanGanem ,

Are you still having trouble with this? If so please post the full stacktrace
