### ISSUE TITLE
AttentionLayer does not support model.save() and load_model()

### ISSUE THREAD

**Issue by sharan21** [thushv89/attention_keras#19]
Not able to use the load_model() function in Keras, as the AttentionLayer() definition does not have get_config() for proper saving of model.
More details on this problem: https://github.com/keras-team/keras/issues/4871
For now, I can only use save_weights() and load_weights() for this custom layer, for which the model has to be built first every time it's loaded.
If anyone has a modified version that supports this please consider merging with main branch

**Comment by thushv89** [comment]
@sharan21 , 

Thanks for pointing this out. I'll be working on this.

**Comment by thushv89** [comment]
Model saving should be fine. There's no reason to implement `get_config` as that will be inherited from the base `Layer` object. But you need to pass the `custom_objects` argument as

`full_model = load_model(os.path.join('..', 'h5.models', 'nmt.h5'), custom_objects={'AttentionLayer': AttentionLayer})`
