### ISSUE TITLE
are some utils missing?

### ISSUE THREAD

**Issue by thegallier** [thushv89/attention_keras#2]
from utils.data_helper import read_data, sents2sequences

Thanks

**Comment by thushv89** [comment]
Hi @thegallier,
Yes that's missing. Thank you for pointing it out. I'll upload the missing part by today.

**Comment by thushv89** [comment]
I have committed all the required module. It should be fixed. Let me know if you still have any issues.

**Comment by leloykun** [comment]
I still keep on getting "No module named 'utils'"

**Comment by thushv89** [comment]
Hi @leloykun ,
It was due to not including project directory in the system path. Should work now
