### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'layer'

### ISSUE THREAD

**Issue by Sum02dean** [thushv89/attention_keras#21]
Hi, I get the following error message. Can you help resolve this?
Thanks.

Dean

Code:
```
from keras.layers import Bidirectional, CuDNNLSTM
from keras.callbacks import History, ReduceLROnPlateau, EarlyStopping
from keras.optimizers import RMSprop, Adam
from keras import regularizers

#callbacks
h = History()
rlr = ReduceLROnPlateau(monitor='val_loss', factor=0.5,patience=10, min_lr=0.000001, verbose=1, min_delta=1e-5)
es = EarlyStopping(monitor='val_loss', min_delta=1e-6, patience=10, verbose=0, mode='auto')


#---------------------- Encoder--------------------------#
#peviously used 250
lstm_dim = 500
input_shape= pr_train.shape[1:]

#input shape
encoder_input = Input(shape=input_shape)

#first encoder layer
encoder_LSTM = Bidirectional(CuDNNLSTM(lstm_dim // 2, return_state=True, return_sequences=True, name='bd_enc_LSTM_01'))
encoder1_output, forward_h1, forward_c1, backward_h1, backward_c1 = encoder_LSTM (encoder_input)


#second encoder layer
encoder_LSTM2 = Bidirectional(CuDNNLSTM(lstm_dim // 2, return_state=True, return_sequences=True, name='bd_enc_LSTM_02'))
encoder2_output, forward_h2, forward_c2, backward_h2, backward_c2 = encoder_LSTM2 (encoder1_output)

# Concatenate all states together
encoder_states = Concatenate(axis=-1)([forward_h1, forward_c1, forward_h2, forward_c2,
                                       backward_h1, backward_c1, backward_h2, backward_c2])

encoder_dense = Dense(lstm_dim, activation='relu', name="enc_dense")(encoder_states)

#---------------------- Decoder--------------------------#

#states for the first LSTM layer
decoder_input = Input(shape=(None, len(charset))) #teacher training
dense_h = Dense(lstm_dim, activation='relu', name="dec_dense_h1")
dense_c = Dense(lstm_dim, activation='relu', name="dec_dense_c1")
state_h = dense_h(encoder_dense)
state_c = dense_c(encoder_dense)
states1 =[state_h, state_c]


#states for the second LSTM layer
dense_h2 = Dense(lstm_dim, activation='relu', name="dec_dense_h2")
dense_c2 = Dense(lstm_dim, activation='relu', name="dec_dense_c2")
state_h2 = dense_h2(encoder_dense)
state_c2 = dense_c2(encoder_dense)
states2 =[state_h2, state_c2]

#this goes through a decoding lstm
decoder_LSTM1 = CuDNNLSTM(lstm_dim, return_sequences=True, name='bd_dec_LSTM_01')
decoder1_output = decoder_LSTM1(decoder_input, initial_state=states1)


#couple the first LSTM with the 2nd LSTM
decoder_LSTM2 = CuDNNLSTM(lstm_dim, return_sequences=True, name='bd_dec_LSTM_02')
decoder2_output = decoder_LSTM2(decoder1_output, initial_state=states2) 

#attention layers
attn_layer = AttentionLayer(name='attention_layer')
attn_out, attn_states = attn_layer([encoder2_output, decoder2_output])
decoder_concat_input = Concatenate(axis=-1, name='concat_layer')([decoder_out, attn_out])


#pass hidden states of decoder2_outputs to dense layer with softmax
decoder_dense = Dense(len(charset), activation='softmax', name="dec_dense_softmax")
decoder_out = decoder_dense (decoder_concat_input)



#----------------------compilations------------#

#model compilation (canonical)
model = Model(inputs=[encoder_input, decoder_input], outputs=[decoder_out])
#Run training
start = time.time()
opt=Adam(lr=0.01) #try 0.005
#test other optimizers (rmsprop)
model.compile(optimizer=opt, loss='categorical_crossentropy')

#fit
model.fit(x=[pr_train, rx_train], 
          y=rx_target, 
          batch_size=250, 
          epochs=2,
          shuffle = True,
          validation_split=0.2,
          callbacks = [h, rlr, es])

end = time.time()
print(end - start)

```
Error:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-165-c2269e41013e> in <module>
>      64 #attention layers
>      65 attn_layer = AttentionLayer(name='attention_layer')
> ---> 66 attn_out, attn_states = attn_layer([encoder2_output, decoder2_output])
>      67 decoder_concat_input = Concatenate(axis=-1, name='concat_layer')([decoder_out, attn_out])
>      68 
> 
> ~/miniconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
>     661               kwargs.pop('training')
>     662             inputs, outputs = self._set_connectivity_metadata_(
> --> 663                 inputs, outputs, args, kwargs)
>     664           self._handle_activity_regularization(inputs, outputs)
>     665           self._set_mask_metadata(inputs, outputs, previous_mask)
> 
> ~/miniconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in _set_connectivity_metadata_(self, inputs, outputs, args, kwargs)
>    1706     kwargs.pop('mask', None)  # `mask` should not be serialized.
>    1707     self._add_inbound_node(
> -> 1708         input_tensors=inputs, output_tensors=outputs, arguments=kwargs)
>    1709     return inputs, outputs
>    1710 
> 
> ~/miniconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in _add_inbound_node(self, input_tensors, output_tensors, arguments)
>    1793     """
>    1794     inbound_layers = nest.map_structure(lambda t: t._keras_history.layer,
> -> 1795                                         input_tensors)
>    1796     node_indices = nest.map_structure(lambda t: t._keras_history.node_index,
>    1797                                       input_tensors)
> 
> ~/miniconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/util/nest.py in map_structure(func, *structure, **kwargs)
>     513 
>     514   return pack_sequence_as(
> --> 515       structure[0], [func(*x) for x in entries],
>     516       expand_composites=expand_composites)
>     517 
> 
> ~/miniconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/util/nest.py in <listcomp>(.0)
>     513 
>     514   return pack_sequence_as(
> --> 515       structure[0], [func(*x) for x in entries],
>     516       expand_composites=expand_composites)
>     517 
> 
> ~/miniconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in <lambda>(t)
>    1792             `call` method of the layer at the call that created the node.
>    1793     """
> -> 1794     inbound_layers = nest.map_structure(lambda t: t._keras_history.layer,
>    1795                                         input_tensors)
>    1796     node_indices = nest.map_structure(lambda t: t._keras_history.node_index,
> 
> AttributeError: 'tuple' object has no attribute 'layer'

**Comment by Sum02dean** [comment]
It was  a coding error on my behalf.

**Comment by Monicakun** [comment]
Hi, I also have the same error. Could you please tell me the location of your coding error?

**Comment by hqsiswiliam** [comment]
> Hi, I also have the same error. Could you please tell me the location of your coding error?

I encountered this problem as well. For me, I revised all `from keras import ...` to `from tensorflow.python.keras import ...` that solved the problem.
