### ISSUE TITLE
AttributeError: 'tuple' object has no attribute '_keras_shape'

### ISSUE THREAD

**Issue by bigbizze** [thushv89/attention_keras#3]
I'm getting this error when using this code:

```
def adjust(x):
     return K.cast(K.reshape(x, (batch_size, 697, 64)), dtype='float32')

input_1 = Input(shape=(maxlen,), name="input1")
x_ = Embedding(vocab_size, embed_size, weights=[embed], name='embedding_1', trainable=False)(input_1)
encoder_out, forward_h, backward_h = Bidirectional(GRU(32, return_sequences=True, return_state=True))(_x)
decoder_out, forward_h, backward_h = Bidirectional(GRU(32, return_sequences=True, return_state=True))(_x, initial_state=[forward_h, backward_h])
encoder_out = Lambda(adjust)(encoder_out)
decoder_out = Lambda(adjust)(decoder_out)
attn_out, attn_states = AttentionLayer()([encoder_out, decoder_out])
a = concatenate([decoder_out, attn_out], axis=1)
```

I'm under the impression this has something to do with how I'm reshaping the encoder & decoder inputs but when I don't reshape them to give a defined shape their shape is == to (?, ?, 64) and I get the error "ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, 64)" followed by "TypeError: __int__ returned non-int (type NoneType)".

When I use:

```
def adjust(x):
     return K.cast(tf.shape(x), dtype='float32')
```

Instead, my encoder & decoder shapes become (3,) which is quite confusing.

I'm assuming that this is my mistake but if it isn't then I thought i'd make you aware of it! Great repository btw! I appreciate all & any advice!

**Comment by thushv89** [comment]
Might be something with the way Bidirectional layer works. I'll look into this.

**Comment by thushv89** [comment]
Hi @bigbizze ,

Can you post your full code? The code above doesn't have the full code (e.g. what is _x?). However, I checked this code by adding some parts myself. I think the issue rises **when batch size is not defined**. I will look into this to see if I can have the batch size undefined and still get this layer to work.

**Comment by thushv89** [comment]
If this is related to batch size the commit ae4b7 should fix the issue.
