### ISSUE TITLE
TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [1, Dimension(None)]. Consider casting elements to a supported type.

### ISSUE THREAD

**Issue by redtea0** [thushv89/attention_keras#9]
**I try to add your attention layer into my encoder-decoder model. the code is like this** 

latent_dim = 256 # LSTM hidden units
dropout = .20 
encoder_inputs = Input(shape=(None, n_inputs), name='encoder_inputs') 
encoder_lstm = LSTM(latent_dim, dropout=dropout, return_sequences=True, return_state=True, name='encoder_lstm')
encoder_outputs, state_h, state_c = encoder_lstm(encoder_inputs)
encoder_states = [state_h, state_c]
decoder_inputs = Input(shape=(None, n_outputs), name='decoder_inputs') 

decoder_lstm = LSTM(latent_dim, dropout=dropout, return_sequences=True, return_state=True, name='decoder_lstm')
decoder_outputs, _, _ = decoder_lstm(decoder_inputs, initial_state=encoder_states)

attn_layer = AttentionLayer(name='attention_layer')
attn_outputs, attn_states = attn_layer([encoder_outputs, decoder_outputs])

decoder_concat_inputs = Concatenate(axis=-1, name='concat_layer')([decoder_outputs, attn_outputs])

decoder_dense = Dense(n_outputs, activation='softmax', name='softmax_layer') # 1 continuous output at each timestep
decoder_outputs = decoder_dense(decoder_concat_inputs)

model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

**but i meet the error like**

 TypeError                                 Traceback (most recent call last)
/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    526     try:
--> 527       str_values = [compat.as_bytes(x) for x in proto_values]
    528     except TypeError:

/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py in <listcomp>(.0)
    526     try:
--> 527       str_values = [compat.as_bytes(x) for x in proto_values]
    528     except TypeError:

/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/compat.py in as_bytes(bytes_or_text, encoding)
     60     raise TypeError('Expected binary or unicode string, got %r' %
---> 61                     (bytes_or_text,))
     62 

TypeError: Expected binary or unicode string, got 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-42-8488a2e4f458> in <module>()
     29 # define attention layer
     30 attn_layer = AttentionLayer(name='attention_layer')
---> 31 attn_outputs, attn_states = attn_layer([encoder_outputs, decoder_outputs])
     32 
     33 # concatenate attention output and decoder output as an input to the softmax layer

~/.local/lib/python3.6/site-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    455             # Actually call the layer,
    456             # collecting output(s), mask(s), and shape(s).
--> 457             output = self.call(inputs, **kwargs)
    458             output_mask = self.compute_mask(inputs, previous_mask)
    459 

<ipython-input-38-725b5b4c250e> in call(self, inputs, verbose)
     95 
     96         fake_state_c = create_inital_state(encoder_out_seq, encoder_out_seq.shape[-1])
---> 97         fake_state_e = create_inital_state(encoder_out_seq, encoder_out_seq.shape[1])  # <= (batch_size, enc_seq_len, latent_dim
     98 
     99         """ Computing energy outputs """

<ipython-input-38-725b5b4c250e> in create_inital_state(inputs, hidden_size)
     91             fake_state = K.sum(fake_state, axis=[1, 2])  # <= (batch_size)
     92             fake_state = K.expand_dims(fake_state)  # <= (batch_size, 1)
---> 93             fake_state = K.tile(fake_state, [1, hidden_size])  # <= (batch_size, latent_dim
     94             return fake_state
     95 

~/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in tile(x, n)
   2189     if isinstance(n, int):
   2190         n = [n]
-> 2191     return tf.tile(x, n)
   2192 
   2193 

/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py in tile(input, multiples, name)
   8803   if _ctx is None or not _ctx._eager_context.is_eager:
   8804     _, _, _op = _op_def_lib._apply_op_helper(
-> 8805         "Tile", input=input, multiples=multiples, name=name)
   8806     _result = _op.outputs[:]
   8807     _inputs_flat = _op.inputs

/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    511           except TypeError as err:
    512             if dtype is None:
--> 513               raise err
    514             else:
    515               raise TypeError(

/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    508                 dtype=dtype,
    509                 as_ref=input_arg.is_ref,
--> 510                 preferred_dtype=default_dtype)
    511           except TypeError as err:
    512             if dtype is None:

/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype, ctx)
   1144 
   1145     if ret is None:
-> 1146       ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
   1147 
   1148     if ret is NotImplemented:

/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    227                                          as_ref=False):
    228   _ = as_ref
--> 229   return constant(v, dtype=dtype, name=name)
    230 
    231 

/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name, verify_shape)
    206   tensor_value.tensor.CopyFrom(
    207       tensor_util.make_tensor_proto(
--> 208           value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    209   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    210   const_tensor = g.create_op(

/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    529       raise TypeError("Failed to convert object of type %s to Tensor. "
    530                       "Contents: %s. Consider casting elements to a "
--> 531                       "supported type." % (type(values), values))
    532     tensor_proto.string_val.extend(str_values)
    533     return tensor_proto

TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [1, Dimension(None)]. Consider casting elements to a supported type.

**Do you have any idea to solve that?  THX a lot!**

**Comment by MaukWM** [comment]
I was getting the same error. I fixed this by changing the import from `from keras.layers import Input, GRU, Dense, Concatenate, TimeDistributed
from keras.models import Model`

to

`from tensorflow.python.keras.layers import Input, GRU, Dense, Concatenate, TimeDistributed
from tensorflow.python.keras.models import Model`

The issue seems to come from the fact that the keras layers do not give the full context of the shape to the Attention layer. Your model could not convert the list to a Tensor because there was a None type within (which is supposed to be a part of a shape).

**Comment by redtea0** [comment]
I changed all my imports by using tensorflow.python.keras.layers but I got the same error.......

**Comment by redtea0** [comment]
> I was getting the same error. I fixed this by changing my imports from
> 
> `from keras.layers import Input, GRU, Dense, Concatenate, TimeDistributed from keras.models import Model`
> 
> to
> 
> `from tensorflow.python.keras.layers import Input, GRU, Dense, Concatenate, TimeDistributed from tensorflow.python.keras.models import Model`
> 
> The issue seems to come from the fact that the keras layers do not give the full context of the shape to the Attention layer. Your model could not convert the list to a Tensor because there was a None type within (which is supposed to be a part of a shape).

I changed all my imports by using tensorflow.python.keras.layers but I got the same error.......

**Comment by habom2310** [comment]
I also got that problem, changing to tensorflow.python.keras.layers didn't solve

**Comment by MaukWM** [comment]
I took another look and the solution @habom2310 proposes should fix the problem.

**Comment by redtea0** [comment]
@MaukWM @habom2310 thx guys, that works!

**Comment by thushv89** [comment]
@MaukWM , @habom2310 and @redtea0 ,

Apologies about the delay and lack of following up. 

Yes, as some of you pointed out. You can only leave `batch_size` as None. All the other dimensions (i.e. `sequence lenth` and `n_inputs` needs to be fixed. This is because there are several reshaping steps performed during attention computation. And having more than one dimension set to None, it is impossible to compute the original shape from the reshaped input. 

Hope that clears things up.

**Comment by amanagr** [comment]
Using both solutions together worked for me.

**Comment by theAB316** [comment]
As mentioned by @amanagr, using both solutions worked for me.
1. Adding a constant value instead on None 
2. Changing the Keras related imports like,` from keras.layers import` to `from tensorflow.keras.layers import`

**Comment by Tam678** [comment]
@thushv89 ,hello,i met the same error.I try to solve the problem via solutions above.But how to add a constant value instead demension(3)?
